name: Java CD with Gradle


on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
  release:
    runs-on: macos-latest
    steps:
      - name: Git Semantic Version
          uses: PaulHatch/semantic-version@v5.0.0-beta
          with:
            tag_prefix: "v"
            major_pattern: "(MAJOR)"
            major_regexp_flags: ""
            minor_pattern: "(MINOR)"
            minor_regexp_flags: ""
            bump_each_commit: false
            search_commit_body: false
            user_format_type: "json"
      - name: Release with Gradle
        id: release
        run: |
          ./gradlew release -Prelease.useAutomaticVersion=true \
          -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
          -Prelease.newVersion=${{ env.NEXT_VERSION }}